# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZkeqOR2VfwHwPcJ_lrjofTxNrOazWku
"""

print ('Площадь прямоугольника')
print('_________')
a=int(inport('Введите значение стороны А: '))
b=int(inport('Введите заначение стороны В:'))
print('-----------')
print('Площадь фигуры -',a*b)